version: 2

jobs:
  deploy:
    docker:
      - image: node:8
    steps:
      - checkout
      - run: npm i
      - run: npm run build
      - run: echo "$NPMRC" > ~/.npmrc
      - run: npm publish

workflows:
  version: 2
  deploy_to_npm:
    jobs:
      - deploy:
          context: reaction-publish-semantic-release
          filters:
            # only run deploy on tags with format: v1.2.3
            tags:
              only: /^v[0-9]+\.[0-9]+\.[0-9]/
            # don't deploy on plain branch pushes
            branches:
              ignore: /.*/
